### ISSUE TITLE
Explain (or omit) -u flag in documentation

### ISSUE THREAD

**Issue by diggy** [combell/autogit-reference#2]
I know at least one other guy with a Github repo who ran into trouble by blindly following the instructions :)

**Comment by coudenysj** [comment]
What trouble did he/she ran into? The -u merely sets the upstream as the tracking branch.

**Comment by diggy** [comment]
I ran into some sort of conflict myself, however fail to remember the exact issue.. But still, specifically in the case of an existing repo with a remote on Github or any other platform, I think you do not want the Combell instance to be the default. Pushing, pulling and merging happens through interaction with that platform, there will never be the need to pull from the Combell remote (i.e. use autogit solely for deployment).

**Comment by coudenysj** [comment]
You are right @diggy, I removed the flag in the documentation for existing repositories.

Thanks!
