### ISSUE TITLE
SSH connection not closed after git push to Combell remote?

### ISSUE THREAD

**Issue by diggy** [combell/autogit-reference#3]
This issue has been occurring since we adopted autogit in our workflow, but I never took the time to report it.

It seems a `git push` to the Combell remote launches two SSH processes, one of which keeps running after successful deployment.

When switching to another (local) repo, committing and pushing to Combell, the command is sent to the wrong server, because of the active, previous connection, resulting in a git error message.

The only way to prevent this is to terminate the SSH process manually in between project deployments (e.g. via the macOS activity monitor app).

If this is intended behavior, feel free to close this issue, otherwise it would be nice if someone could look into this :)

**Comment by coudenysj** [comment]
Hi @diggy, this definitely isn't the intended behavior and is something that should not happen.

It sounds like something your machine is doing, because the 2 processes are initiated there. I've tested it on my (linux) machine, and only 1 connection is created to push to the Combell remote.

Is it possible you might have some custom SSH settings (e.g. ControlMaster)?

**Comment by diggy** [comment]
@coudenysj Yes, I can confirm we have a customized SSH setup (actually a relict of previous deploy system, where the need to leverage `ControlMaster` became a necessity). Here are the relevant entries for Combell:

```
Host ssh.*
  ControlPath ~/.ssh/controlmasters/%%h-%%p-%%r
  ControlMaster auto
  ControlPersist 10m
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
  IdentityFile ~/.ssh/some_rsa_key
  UseKeychain yes
Host *.webhosting.be
  ControlPath ~/.ssh/controlmasters/%%h-%%p-%%r
  ControlMaster auto
  ControlPersist 10m
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
  IdentityFile ~/.ssh/some_rsa_key
  UseKeychain yes
```

**Comment by coudenysj** [comment]
@diggy It looks like your ControlPath setting isn't dynamic.

Instead of using the %h, %p & %r variables, you're effectively escaping the % sign by using 2 % sings.

Is the issue resolved when you change the setting to `~/.ssh/controlmasters/%h-%p-%r`?

**Comment by diggy** [comment]
@coudenysj thanks, I'll be deploying later today, so I'll check and will let you know.

**Comment by diggy** [comment]
@coudenysj tried your suggestion, but no dice. Removing the line `ControlPersist 10m` however effectively fixes the issue (makes sense actually). The persistence was originally needed to prevent ssh timeout during deployment, switching to autogit seems to have made this problem go away.
